name: Build Windows Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Build Notification Executable
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cl.exe /EHsc /std:c++17 /O1 /Os /GL win10_notifier.cpp /link /SUBSYSTEM:WINDOWS user32.lib ole32.lib shell32.lib runtimeobject.lib /OPT:REF /OPT:ICF
        dir
    
    - name: Convert Executable to Base64
      run: |
        $bytes = [System.IO.File]::ReadAllBytes("$env:GITHUB_WORKSPACE\win10_notifier.exe")
        $base64 = [System.Convert]::ToBase64String($bytes)
        echo "EXECUTABLE_BASE64=$base64" >> $env:GITHUB_ENV
      shell: pwsh
    
    - name: Output Base64 Executable
      run: |
        echo "::notice::Executable Base64 (copy everything between START and END markers)"
        echo "::notice::START_EXECUTABLE_BASE64"
        echo "${{ env.EXECUTABLE_BASE64 }}"
        echo "::notice::END_EXECUTABLE_BASE64"
