name: Build Windows Notifier

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Build Notification Executable
      shell: cmd
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
        cl.exe /EHsc /std:c++17 /O1 /Os /GL wintoast.cpp /link /SUBSYSTEM:WINDOWS user32.lib ole32.lib shell32.lib runtimeobject.lib /OPT:REF /OPT:ICF
        dir
    
    - name: Check if executable exists
      run: |
        if (Test-Path -Path "wintoast.exe") {
          echo "Executable exists"
        } else {
          echo "Executable does not exist"
          exit 1
        }
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      continue-on-error: true
      with:
        files: wintoast.exe
        name: Windows Notifier
        tag_name: v1.0.${{ github.run_number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
